### ISSUE TITLE
additional U.S. Open Government Partnership commitment on "open source software policy"

### ISSUE THREAD

**Issue by tvol** [unitedstates/licensing#30]
Hey all--saw an interesting update to the U.S. Open Government Partnership commitments--http://www.whitehouse.gov/sites/default/files/microsites/ostp/new_nap_commitments_report_092314.pdf

"Adopt an open source software policy. Using and contributing back to open source software can fuel innovation, lower costs, and benefit the public. No later than December 31, 2015, the Administration will work through the Federal agencies to develop an open source software policy that, together with the Digital Services Playbook, will support improved access to custom software code developed for the 
Federal government."

Wondering if anyone knows how this will work, who's responsible from the Administration, and if/how our best practices for marking license-free would apply.

**Comment by konklone** [comment]
I'm not sure of the complete answer to those questions, but I think it's fair to assume OSTP, the CTO's office, and (since the Playbook is mentioned) USDS will all have a hand in it. Those offices' reception to our license-free best practices has seemed positive, and I can personally attest that it shaped [the licensing aspect](https://github.com/18F/open-source-policy/blob/master/policy.md#open-source-licenses) of the open source policy 18F published a couple months back. (All 18F's stuff is marked PD + int'l CC0.)
